draw_sprite(spr_ControlButton, 0, 1506, 920);
draw_set_halign(fa_center);
draw_set_valign(fa_center);
draw_set_color(c_aqua);
draw_set_font(fnt_title);
//draw_sprite(spr_selectArrow,0,1506-260, 989);
draw_text_transformed(960, 200, "Use the arrow keys to move.", .5, .5, image_angle);
draw_text_transformed(960, 240, "Press Q to send your ghost out.", .5, .5, image_angle);
draw_text_transformed(960, 280, "While your ghost is out, you only control it.", .5, .5, image_angle);
draw_text_transformed(960, 320, "Press Q again to recall your ghost.", .5, .5, image_angle);
draw_text_transformed(960, 360, "Press 1, 2, 3, or 4 to send a decoy to the ghost.", .5, .5, image_angle);
draw_text_transformed(960, 400, "1 = Purple, 2 = Green, 3 = Blue, 4 = Red", .5, .5, image_angle);
draw_text_transformed(960, 440, "Purple decoy simply walks and distracts enemies.", .5, .5, image_angle);
draw_text_transformed(960, 480, "Green decoy makes a sound blast when he reaches his destination.", .5, .5, image_angle);
draw_text_transformed(960, 520, "Blue decoy is invisible until he reaches his destination.", .5, .5, image_angle);
draw_text_transformed(960, 560, "Red decoy kills the first enemy that attacks him.", .5, .5, image_angle);
draw_text_transformed(960, 600, "You can only send out each decoy once per level!", .5, .5, image_angle);
draw_text_transformed(960, 640, "Get the key to open the door.", .5, .5, image_angle);
draw_text_transformed(960, 680, "Get to the door to go to the next level.", .5, .5, image_angle);
draw_text_transformed(960, 720, "Press R to restart a level", .5, .5, image_angle);
draw_text(1506,989, "Back");